### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by systemsathomesdotcom**
Skip the foreach() loop when $prototype_vals is a non-array, as when get_sites() returns NULL.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
To avoid the conditional, could we just set `$prototype_vals` as an array when null?

**Comment by systemsathomesdotcom** [comment]
We could; I tend to prefer faster code over simpler code.

I'll make an alternative patch.

**Comment by danielbachhuber** [comment]
> I tend to prefer faster code over simpler code.

How is one faster than the other?

**Comment by systemsathomesdotcom** [comment]
It's faster to skip the loop than to set the variable upon which it depends and then run it zero times.  But whichever solution you prefer is okay by me.

**Comment by danielbachhuber** [comment]
> It's faster to skip the loop than to set the variable upon which it depends and then run it zero times.

Link?

**Comment by systemsathomesdotcom** [comment]
Test for yourself:
    <?php
      function test1() {
        $var = FALSE;
        if (!is_array($var)) {
          $var = array();
        } 
        foreach ($var as $key => $value) {
          print "Do something\n";
        } 
      } 
      function test2() {
        $var = FALSE;
        if (is_array($var)) {
          foreach ($var as $key => $value) {
            print "Do something\n";
          } 
        } 
      } 
      $start = microtime(true);
      for ($i = 1; $i <= 10000; $i++) {
        test1();
      } 
      $elapsed1 = microtime(true) - $start;
      print "Test 1: $elapsed1\n";
      $start = microtime(true);
      for ($i = 1; $i <= 10000; $i++) {
        test2();
      } 
      $elapsed2 = microtime(true) - $start;
      print "Test 2: $elapsed2\n";
      $ratio = $elapsed1 / $elapsed2;
      print "Test1/Test2: $ratio\n";

**Comment by danielbachhuber** [comment]
Fair enough — thanks for the test :)

**Pull request merged**
